version: '3'

services:
  ad-server-postgres:
    image: postgres:9-alpine
    container_name: ad-server-postgres
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: ${DB_DATABASE}
    tmpfs:
      - /data
    ports:
      - ${DB_PORT}:5432
    logging:
      driver: none
